export const IS_AUTH = "IS_AUTH";
export const GET_LOGIN = "GET_LOGIN";
export const REQUEST_FETCH_TOLOGIN = "REQUEST_FETCH_TOLOGIN";
export const RECEIVE_FETCH_TOLOGIN = "RECEIVE_FETCH_TOLOGIN";
export const REQUEST_FETCH_TOSIGNUP = "REQUEST_FETCH_TOSIGNUP";
export const RECEIVE_FETCH_TOSIGNUP = "RECEIVE_FETCH_TOSIGNUP";
export const CHANGE_MODAL = "CHANGE_MODAL";

