export const IS_AUTH = "IS_AUTH";
export const GET_LOGIN = "GET_LOGIN";
export const REQUEST_FETCH_TOLOGIN = "REQUEST_FETCH_TOLOGIN";
export const RECEIVE_FETCH_TOLOGIN = "RECEIVE_FETCH_TOLOGIN";
export const REQUEST_FETCH_TOSIGNUP = "REQUEST_FETCH_TOSIGNUP";
export const RECEIVE_FETCH_TOSIGNUP = "RECEIVE_FETCH_TOSIGNUP";
export const CHANGE_MODAL = "CHANGE_MODAL";
export const ADD_ACCOUNT_HESHTEGS = "ADD_ACCOUNT_HESHTEGS";
export const SAVE_PRESENT = "SAVE_PRESENT";
export const CHANGE_PRESENT = "CHANGE_PRESENT";
export const USER_NAME="USER_NAME"
export const USER_MIDDLE_NAME="USER_MIDDLE_NAME"
export const USER_FAMILY_NAME="USER_FAMILY_NAME"
export const USER_EMAIL="USER_EMAIL"
export const USER_INFO="USER_INFO"
export const REQUEST_FETCH_TOCHANGEINFO = "REQUEST_FETCH_TOCHANGEINFO";
export const RECEIVE_FETCH_TOCHANGEINFO = "RECEIVE_FETCH_TOCHANGEINFO";
export const USER_AVATAR="USER_AVATAR";
export const USER_DATES="USER_DATES";
export const USER_BIRTHDATE="USER_BIRTHDATE"


